
version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/web.dockerfile
    working_dir: /var/www
    depends_on:
      - app
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www
  app:
    build:
      context: .
      dockerfile: ./.docker/app.dockerfile
    depends_on:
      - db
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=app_dev
      - DB_USERNAME=app_user
      - DB_PASSWORD=1q2w3e
      - TZ=America/Sao_Paulo
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e
      MYSQL_DATABASE: app_dev
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1q2w3e
  pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "9797:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1q2w3e
  mailhog:
    depends_on:
      - db
      - app
      - web
    image: mailhog/mailhog:latest
    ports:
      - "10007:8025"
volumes:
  mysql_data:
      driver: local
networks:
  default:
    driver: bridge
